### PR TITLE
Build on windows

### PR DESCRIPTION
**Pull request by inkydragon**
test both `2018` & `rogue`
- `gcc` on wsl
    `gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)`
- `cl` for MSVC
    `x64 19.16.27035`
- `gcc` on mingw64
    `gcc version 8.1.0 (x86_64-win32-seh-rev0, Built by MinGW-W64 project)`

----

`CLEAR_STRING	.STRINGZ	"\e[2J\e[H\e[3J"` doesn't work on windows, 
we may provide a new Instruction to do this.

### CODE REVIEW

**Comment by justinmeiners** [comment]
This is really great! I am so glad someone finally did this!

I do want to take a slightly different approach though. I want to make a separate section of the .lit file which contains the windows code, and then output a separate .c file windows (similar to the alternate cpp version.) This will remove the need for `#ifndef` for windows code and make the tutorial more readable.

Which of these sounds like a good option to you?
1. I make the recommended changes to your code, but I will need your help to test when I am done.
2. You make the recommended changes. I know you already did a lot of work, and may not want to do more, but want to make it available.

I am perfectly happy to do 1 because I want to include your contributions, it just may take a few weeks.

**Comment by justinmeiners** [comment]
Actually, disregard, I did it right now. 
See PR on your fork

**Comment by inkydragon** [comment]
Everything works well on windows.

I am also update `Makefile`, add a new flag to make it more clearly.
You may test it on *nix system, it works well for me on WSL(ubuntu).
If something goes wrong, you may update `lit` program.

**Review by rpendleton — APPROVED** [review]

**Comment by justinmeiners** [comment]
Looks good! thanks again for making this better!

**Pull request merged**
