### PR TITLE
added a new python implementation.

### PR DESCRIPTION
**Pull request by mhashim6**
following this tutorial, we were able to create a modular python implementation for LC-3 for a school assignment. Thanks!

### CODE REVIEW

**Comment by justinmeiners** [comment]
Looks good. Thanks for contributing.

Just curious, did your school assign this?

**Comment by mhashim6** [comment]
Thanks!
It's a computer organization class.
The professor didn't assign this project specificly, he just wanted us to practice team work on any project (even if it has nothing to do with Computer organization).

But I found LC-3 to be the perfect project for such class, and the professor accepted our proposal. So... It's kind of.

**Comment by justinmeiners** [comment]
Cool! I hope it was helpful.

**Comment by mhashim6** [comment]
It was really helpful, thanks!

**Pull request merged**
