### PR TITLE
Added another Rust implementation entry

### PR DESCRIPTION
**Pull request by atul-g**

### CODE REVIEW

**Comment by justinmeiners** [comment]
Thanks, I will look at this soon. Ryan and I might be changing how we show contributions and will let you know.

**Comment by atul-g** [comment]
Sure! Thanks for your article btw :)

**Comment by justinmeiners** [comment]
We are changing to use Github topics. Just make sure your project has the topic "lc3" and it will get included.

**Comment by atul-g** [comment]
Just to be clear, are you referring to the Github Topics for my fork for this PR? Because my [Github repo of the rust implentation](https://github.com/atul-g/rust_vm) already has the "lc3" topic tag.

**Comment by rpendleton** [comment]
We're referring to the topics for your implementation repository, so you should be good to go.

We'll be linking to the GitHub topic page in the article: https://github.com/topics/lc3?l=rust

**Comment by atul-g** [comment]
Oh alright, thanks!

**Pull request closed without merging**
